-- Add private guest photos without changing the public wedding-media bucket.
alter table public.photo_submissions
  add column if not exists visibility text not null default 'public';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.photo_submissions'::regclass
      and conname = 'photo_visibility_allowed'
  ) then
    alter table public.photo_submissions
      add constraint photo_visibility_allowed
      check (visibility in ('public', 'private')) not valid;
  end if;
end;
$$;

create index if not exists photos_visibility_recent
  on public.photo_submissions(wedding_id, visibility, created_at desc);

-- Preserve the established public path forms and permit only the new private
-- path form generated by the guest-submit Edge Function.
alter table public.photo_submissions
  drop constraint if exists photo_path_matches_wedding;
alter table public.photo_submissions
  add constraint photo_path_matches_wedding check (
    storage_path ~ ('^weddings/' || wedding_id::text || '/photos/[0-9A-Fa-f-]+\.(jpg|png|webp)$') or
    storage_path ~ ('^' || wedding_id::text || '/photos/[0-9A-Fa-f-]+\.(jpg|png|webp)$') or
    storage_path ~ ('^' || wedding_id::text || '/private/photos/[0-9A-Fa-f-]+\.(jpg|png|webp)$')
  ) not valid;

-- A private bucket is separate from the existing public bucket. Reapplying
-- this migration keeps this bucket private and retains its upload limits.
do $$
declare existing_bucket_public boolean;
begin
  select public into existing_bucket_public
  from storage.buckets where id = 'wedding-private-media';
  if not found then
    insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
    values ('wedding-private-media', 'wedding-private-media', false, 5242880,
      array['image/jpeg', 'image/png', 'image/webp']);
  elsif existing_bucket_public then
    raise exception 'Bucket wedding-private-media exists but is public; refusing to change its access mode.';
  else
    update storage.buckets set
      file_size_limit = 5242880,
      allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp']
    where id = 'wedding-private-media';
  end if;
end;
$$;

-- The public endpoint and authenticated clients can only see public photo
-- rows unless the caller is an admin for that exact wedding.
drop policy if exists "photos public guest read" on public.photo_submissions;
drop policy if exists "photos authenticated scoped read" on public.photo_submissions;
drop policy if exists "photos select hard boundary" on public.photo_submissions;

create policy "photos public guest read" on public.photo_submissions
  for select to anon using (visibility = 'public');
create policy "photos authenticated scoped read" on public.photo_submissions
  for select to authenticated using (
    (select wedding_private.is_wedding_admin(wedding_id)) or
    (not (select wedding_private.is_any_wedding_admin()) and visibility = 'public')
  );
create policy "photos select hard boundary" on public.photo_submissions
  as restrictive for select to anon, authenticated using (
    visibility = 'public' or
    ((select auth.role()) = 'authenticated' and
     (select wedding_private.is_wedding_admin(wedding_id)))
  );

-- Private object names must contain a canonical wedding UUID and generated
-- photo UUID. Compare against weddings.id as text to avoid unsafe path casts.
drop policy if exists "private wedding media admin read" on storage.objects;
create policy "private wedding media admin read" on storage.objects
  for select to authenticated using (
    bucket_id = 'wedding-private-media' and
    name ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/private/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$' and
    exists (
      select 1 from public.weddings w
      where w.id::text = split_part(storage.objects.name, '/', 1)
        and (select wedding_private.is_wedding_admin(w.id))
    )
  );
drop policy if exists "private wedding media read boundary" on storage.objects;
create policy "private wedding media read boundary" on storage.objects
  as restrictive for select to anon, authenticated using (
    bucket_id <> 'wedding-private-media' or
    ((select auth.role()) = 'authenticated' and
     name ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/private/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$' and
     exists (
       select 1 from public.weddings w
       where w.id::text = split_part(storage.objects.name, '/', 1)
         and (select wedding_private.is_wedding_admin(w.id))
     ))
  );

-- Service-role Edge Function writes bypass Storage RLS. All client writes are
-- denied even if another permissive policy is added later.
drop policy if exists "private wedding media client insert boundary" on storage.objects;
create policy "private wedding media client insert boundary" on storage.objects
  as restrictive for insert to anon, authenticated
  with check (bucket_id <> 'wedding-private-media');
drop policy if exists "private wedding media client update boundary" on storage.objects;
create policy "private wedding media client update boundary" on storage.objects
  as restrictive for update to anon, authenticated
  using (bucket_id <> 'wedding-private-media')
  with check (bucket_id <> 'wedding-private-media');

drop policy if exists "private wedding media admin delete" on storage.objects;
create policy "private wedding media admin delete" on storage.objects
  for delete to authenticated using (
    bucket_id = 'wedding-private-media' and
    name ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/private/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$' and
    exists (
      select 1 from public.weddings w
      where w.id::text = split_part(storage.objects.name, '/', 1)
        and (select wedding_private.is_wedding_admin(w.id))
    )
  );
drop policy if exists "private wedding media delete boundary" on storage.objects;
create policy "private wedding media delete boundary" on storage.objects
  as restrictive for delete to anon, authenticated using (
    bucket_id <> 'wedding-private-media' or
    ((select auth.role()) = 'authenticated' and
     name ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/private/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$' and
     exists (
       select 1 from public.weddings w
       where w.id::text = split_part(storage.objects.name, '/', 1)
         and (select wedding_private.is_wedding_admin(w.id))
     ))
  );
